//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Order_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Order_Line()
        {
            this.Return_Customer_Order_Line = new HashSet<Return_Customer_Order_Line>();
        }
    
        public int Customer_Order_Line_ID { get; set; }
        public Nullable<int> Customer_Order_ID { get; set; }
        public Nullable<int> Quotation_Line_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Customer_Order Customer_Order { get; set; }
        public virtual Quotation_Line Quotation_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_Customer_Order_Line> Return_Customer_Order_Line { get; set; }
    }
}
