//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Design
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Design()
        {
            this.Design_Line = new HashSet<Design_Line>();
            this.Quotation_Request_Line = new HashSet<Quotation_Request_Line>();
        }
    
        public int Design_ID { get; set; }
        public Nullable<int> Product_Type_ID { get; set; }
        public string Design_Name { get; set; }
        public string Additional_Instructions { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Design_Line> Design_Line { get; set; }
        public virtual Product_Type Product_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation_Request_Line> Quotation_Request_Line { get; set; }
    }
}
