//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_Request_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quotation_Request_Line()
        {
            this.Quotation_Line = new HashSet<Quotation_Line>();
        }
    
        public int Request_Line_ID { get; set; }
        public Nullable<int> Request_ID { get; set; }
        public Nullable<int> Design_ID { get; set; }
        public Nullable<int> Product_Size_ID { get; set; }
        public string Colour { get; set; }
        public Nullable<int> Web_Link_ID { get; set; }
        public string Product_Code { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Design Design { get; set; }
        public virtual Product_Size Product_Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation_Line> Quotation_Line { get; set; }
        public virtual Quotation_Request Quotation_Request { get; set; }
        public virtual Web_Link Web_Link { get; set; }
    }
}
